# Generated by Django 3.2.7 on 2021-09-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('rua', models.CharField(db_index=True, max_length=200)),
                ('cidade', models.CharField(db_index=True, max_length=200)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('criado_em',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
